export const applications = [
    {
        id: 1,
        name: 'Messenger - Text & video',
        branch: 'Facebook',
        type: 'application',
        date: '2025-01-20',
    },
    {
        id: 2,
        name: 'WhatsApp Messenger',
        branch: 'WhatsApp Inc',
        type: 'application',
        date: '2025-05-20',
    },
    {
        id: 3,
        name: 'Instagram',
        branch: 'Instagram',
        type: 'application',
        date: '2024-01-20',
    },
    {
        id: 4,
        name: 'Meesho',
        branch: 'Shopping',
        type: 'application',
        date: '2025-01-25',
    },
    {
        id: 5,
        name: 'PhonePay',
        branch: 'Finance',
        type: 'application',
        date: '2025-01-10',
    },
    {
        id: 6,
        name: 'Snapchat',
        branch: 'Communication',
        type: 'application',
        date: '2025-07-20',
    },
    {
        id: 7,
        name: 'TrueCaller',
        branch: 'Communication',
        type: 'application',
        date: '2022-01-20',
    },
    {
        id: 8,
        name: 'Flipkart',
        branch: 'Shopping',
        type: 'application',
        date: '2025-10-20',
    },
    {
        id: 9,
        name: 'Blinkit',
        branch: 'Food & Drinks',
        type: 'application',
        date: '2025-01-12',
    },
    {
        id: 10,
        name: 'Candy Crush',
        branch: 'Puzzle',
        type: 'Games',
        date: '2023-07-20',
    },
    {
        id: 11,
        name: 'Coin Master',
        branch: 'Casino',
        type: 'Games',
        date: '2022-03-20',
    },
    {
        id: 12,
        name: 'Crosswords',
        branch: 'Word-Puzzle',
        type: 'Games',
        date: '2020-01-10',
    },
    {
        id: 13,
        name: 'Carrom League',
        branch: 'Sports',
        type: 'Games',
        date: '2024-05-02',
    },
    {
        id: 14,
        name: 'Subway-Surf',
        branch: 'Action',
        type: 'Games',
        date: '2022-02-18',
    },
    {
        id: 15,
        name: 'Hidden - Objects',
        branch: 'Puzzle',
        type: 'Games',
        date: '2021-11-29',
    },
    {
        id: 16,
        name: 'Chess Online',
        branch: 'Board',
        type: 'Games',
        date: '2023-12-03',
    },
    {
        id: 17,
        name: 'Screw Puzzle',
        branch: 'Puzzle',
        type: 'Games',
        date: '2019-11-29',
    },
    {
        id: 18,
        name: 'Soltaire',
        branch: 'Card',
        type: 'Games',
        date: '2021-04-19',
    },
    {
        id: 19,
        name: 'The Alchemist',
        branch: 'Redables',
        type: 'Books',
        date: '2021-02-10',
    },
    {
        id: 20,
        name: 'Docter Faustus',
        branch: 'Redables',
        type: 'Books',
        date: '2021-06-26',
    },
    {
        id: 21,
        name: 'Pride and Prejudice',
        branch: 'Readables',
        type: 'Books',
        date: '2020-10-02',
    },
    {
        id: 22,
        name: 'Wuthering Heights',
        branch: 'Readables',
        type: 'Books',
        date: '2019-05-17',
    },
    {
        id: 23,
        name: 'Twisted Love',
        branch: 'Readables',
        type: 'Books',
        date: '2025-01-14',
    },
    {
        id: 24,
        name: 'Twisted Games',
        branch: 'Readables',
        type: 'Books',
        date: '2023-11-07',
    },
    {
        id: 25,
        name: 'Twisted Hate',
        branch: 'Readables',
        type: 'Books',
        date: '2022-03-19',
    },
    {
        id: 26,
        name: 'Twisted Lies',
        branch: 'Readables',
        type: 'Books',
        date: '2019-07-13',
    },
    {
        id: 27,
        name: 'The Odyssey',
        branch: 'Readables',
        type: 'Books',
        date: '2024-04-20',
    },
    {
        id: 28,
        name: 'PictoBox',
        branch: 'AI',
        type: 'Children',
        date: '2020-05-17',
    },
    {
        id: 29,
        name: 'Bedtime Stories ',
        branch: 'Redables',
        type: 'Children',
        date: '2018-07-29',
    },
    {
        id: 30,
        name: 'Speak Out',
        branch: 'Kids',
        type: 'Children',
        date: '2023-11-11',
    },
    {
        id: 31,
        name: 'Colouring Book',
        branch: 'Activity',
        type: 'Children',
        date: '2022-12-22',
    },
    {
        id: 32,
        name: 'Piano',
        branch: 'Activity',
        type: 'Children',
        date: '2020-05-20',
    },
    {
        id: 33,
        name: 'Fruit Match',
        branch: 'Puzzle',
        type: 'Children',
        date: '2023-12-25',
    },
    {
        id: 34,
        name: 'Math Games',
        branch: 'Education',
        type: 'Children',
        date: '2021-08-24',
    },
    {
        id: 35,
        name: 'Hangama Kids',
        branch: 'Word Games',
        type: 'Children',
        date: '2019-04-15',
    },
    {
        id: 36,
        name: 'Talking Tom',
        branch: 'Entertainment',
        type: 'Children',
        date: '2022-03-21',
    },
    {
        id: 37,
        name: 'Vocabulary',
        branch: 'Educational',
        type: 'education',
        date: '2023-09-20',
    },
    {
        id: 38,
        name: 'Hello Talk',
        branch: 'Educational',
        type: 'education',
        date: '2022-10-02',
    },
    {
        id: 39,
        name: 'Duolingo',
        branch: 'Educational',
        type: 'education',
        date: '2021-02-16',
    },
    {
        id: 40,
        name: 'IELTS ',
        branch: 'Educational',
        type: 'education',
        date: '2023-12-31',
    },
    {
        id: 41,
        name: 'SpeakX English',
        branch: 'Educational',
        type: 'education',
        date: '2018-07-21',
    },
    {
        id: 42,
        name: 'Udemy',
        branch: 'Educational',
        type: 'education',
        date: '2023-06-19',
    },
    {
        id: 43,
        name: 'Great Learning',
        branch: 'Educational',
        type: 'education',
        date: '2019-03-18',
    },
    {
        id: 44,
        name: 'Quizlet',
        branch: 'Educational',
        type: 'education',
        date: '2021-03-30',
    },
    {
        id: 45,
        name: 'Learn Java',
        branch: 'Educational',
        type: 'education',
        date: '2025-07-20',
    },
    {
        id: 46,
        name: 'Viki: Asian Dramas',
        branch: 'Dramas and Movies',
        type: 'entertainment',
        date: '2023-05-16',
    },
    {
        id: 47,
        name: 'Netflix',
        branch: 'Entertainment',
        type: 'entertainment',
        date: '2024-02-14',
    },
    {
        id: 48,
        name: 'Disney + Hotstar',
        branch: 'Entertainment',
        type: 'entertainment',
        date: '2021-09-12',
    },
    {
        id: 49,
        name: 'Talkie ',
        branch: 'Entertainment',
        type: 'entertainment',
        date: '2023-11-18',
    },
    {
        id: 50,
        name: 'Youtube',
        branch: 'Entertainment',
        type: 'entertainment',
        date: '2024-03-29',
    },
    {
        id: 51,
        name: 'iQIYI',
        branch: 'Entertainment',
        type: 'entertainment',
        date: '2019-04-12',
    },
    {
        id: 52,
        name: 'Airtel Xstream',
        branch: 'Entertainment',
        type: 'entertainment',
        date: '2013-03-17',
    },
    {
        id: 53,
        name: 'My Drama Shots',
        branch: 'Entertainment',
        type: 'entertainment',
        date: '2026-10-04',
    },
    {
        id: 54,
        name: 'IMBD Movies',
        branch: 'Entertainment',
        type: 'entertainment',
        date: '2017-12-25',
    },
    {
        id: 55,
        name: 'Daily Yoga',
        branch: 'Health & Fitness',
        type: 'fitness',
        date: '2013-10-27',
    },
    {
        id: 56,
        name: 'Calorie Counter',
        branch: 'Health & Fitness',
        type: 'fitness',
        date: '2023-12-03',
    },
    {
        id: 57,
        name: 'Jawline Exercise',
        branch: 'Health & Fitness',
        type: 'fitness',
        date: '2025-05-20',
    },
    {
        id: 58,
        name: 'Freelitics',
        branch: 'Health & Fitness',
        type: 'fitness',
        date: '2019-11-29',
    },
    {
        id: 59,
        name: 'MyFitnessPal',
        branch: 'Health & Fitness',
        type: 'fitness',
        date: '2024-04-20',
    },
    {
        id: 60,
        name: 'FitOn',
        branch: 'Health & Fitness',
        type: 'fitness',
        date: '2025-05-20',
    },
    {
        id: 61,
        name: 'Intermitted Fasting',
        branch: 'Health & Fitness',
        type: 'fitness',
        date: '2022-10-02',
    },
    {
        id: 62,
        name: 'Bends & Streches',
        branch: 'Health & Fitness',
        type: 'fitness',
        date: '2023-12-03',
    },
    {
        id: 63,
        name: 'Yoga for Beginners',
        branch: 'Health & Fitness',
        type: 'fitness',
        date: '2024-10-20',
    },
    {
        id: 64,
        name: 'Old Role - Vintage',
        branch: 'Photography',
        type: 'photography',
        date: '2019-11-29',
    },
    {
        id: 65,
        name: 'Magic Eraser',
        branch: 'Photography',
        type: 'photography',
        date: '2022-10-02',
    },
    {
        id: 66,
        name: 'Collage Maker',
        branch: 'Photography',
        type: 'photography',
        date: '2023-04-20',
    },
    {
        id: 67,
        name: 'Photo Editor',
        branch: 'Photography',
        type: 'photography',
        date: '2024-04-20',
    },
    {
        id: 68,
        name: 'HD Camera',
        branch: 'Photography',
        type: 'photography',
        date: '2022-10-02',
    },
    {
        id: 69,
        name: 'PicsArt',
        branch: 'Photography',
        type: 'photography',
        date: '2019-11-29',
    },
    {
        id: 70,
        name: 'Remini',
        branch: 'Photography',
        type: 'photography',
        date: '2024-04-20',
    },
    {
        id: 71,
        name: 'Inshot',
        branch: 'Photography',
        type: 'photography',
        date: '2025-05-20',
    },
    {
        id: 72,
        name: 'Film Maker',
        branch: 'Photography',
        type: 'photography',
        date: '2023-12-03',
    },

]
